# Generated by Django 6.0.7 on 2026-07-09 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('hypo', 'Hypothyroidism'), ('hyper', 'Hyperthyroidism'), ('hashimotos', "Hashimoto's"), ('other', 'Other')], max_length=20)),
                ('diagnosis_date', models.DateField()),
                ('current_medication', models.CharField(max_length=100)),
                ('current_dosage', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_drawn', models.DateField()),
                ('test_type', models.CharField(choices=[('tsh', 'TSH'), ('free_t3', 'Free T3'), ('free_t4', 'Free T4')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reference_range_low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reference_range_high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.condition')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_taken', models.TimeField()),
                ('taken_with_food', models.BooleanField(default=False)),
                ('minutes_from_coffee_or_calcium', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.condition')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('symptom_type', models.CharField(choices=[('fatigue', 'Fatigue'), ('weight_change', 'Weight Change'), ('cold_sensitivity', 'Cold Sensitivity'), ('mood_changes', 'Mood Changes'), ('hair_thinning', 'Hair Thinning'), ('heart_palpitations', 'Heart Palpitations'), ('brain_fog', 'Brain Fog'), ('joint_pain', 'Joint pain')], max_length=30)),
                ('severity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.condition')),
            ],
        ),
    ]
