# Generated by Django 6.0.7 on 2026-09-05 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_alter_condition_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='diagnosis_date',
            new_name='date_of_diagnosis',
        ),
        migrations.RenameField(
            model_name='medicationlog',
            old_name='date',
            new_name='date_taken',
        ),
        migrations.RenameField(
            model_name='symptomlog',
            old_name='date',
            new_name='date_logged',
        ),
        migrations.AlterField(
            model_name='medicationlog',
            name='minutes_from_coffee_or_calcium',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
